**Nama : Imelda Dwi Ardiyana**

In [1]:
import numpy as np

In [23]:
#f(x) = a + 2b + 3c+ 4d - 30

n = 6

#chromosome
#initiation of chromosome
chromosome = np.random.randint(0,30, (n,4))
print("chromosome: ", chromosome)

chromosome:  [[21  1 25 28]
 [ 6 14 26 24]
 [14 26 27  2]
 [ 9 26 14 19]
 [25 15 22 22]
 [19 16 12  9]]


In [24]:
epoch = 0

while epoch <  200 :
    # Computation of fitness function 
    #1/// Perhitungan fungsi
    objective = abs(30 - chromosome[:,0] - 2*chromosome[:,1] -3*chromosome[:,2] -
                    4*chromosome[:,3] )
    print("Fitness object :", objective)
    
    # Selection of fittest chromosome  
    #2///Pemilihan kromosom yang paling cocok

    fitness =  1/(1 + objective)
    print("Fitness :",fitness)
    
    # Calculating the total of fitness function   
    #3/// Menghitung total fungsi kebugaran
    total = fitness.sum()
    print("Total :",total)
    
    # Calculating Probablility for each chromosome  
    #/// Menghitung Probabilitas untuk setiap kromosom
    prob = fitness/total
    print("Probability :",prob)
    
    # Selection using Roulette Wheel And Calculating Cumulative Probability  
    #4/// Seleksi menggunakan Roda Roulette Dan Menghitung Probabilitas Kumulatif
    cum_sum = np.cumsum(prob)
    print("Cumulative Sum :", cum_sum)
    
    # Generating Random Numbers in the range 0-1  
    #/// Menghasilkan Angka Acak dalam kisaran 0-1
    Ran_nums = np.random.random((chromosome.shape[0]))
    print("Random Numbers :",Ran_nums)
    
    # Making a new matrix of chromosome for calculation purpose  
    #//// Membuat matriks kromosom baru untuk tujuan perhitungan
    chromosome_2 = np.zeros((chromosome.shape[0],4))
    
    for i in range(Ran_nums.shape[0]):
        for j in range(chromosome.shape[0]):
            if Ran_nums[i]  < cum_sum[j]:
                chromosome_2[i,:] = chromosome[j,:]
                break
            
    chromosome = chromosome_2
    print("Chromosomes after updation :",chromosome)
        
    # crossover  
    #5/// penyeberangan
    R = [np.random.random() for i in range(n)]
    print("Random Values :",R)
    
    # Crossover Rate  
    #/// Tingkat Crossover
    pc = 0.25
    flag = Ran_nums < pc
    print("Flagged Values :",flag)
    
    # Determining the cross chromosomes  
    #/// Menentukan kromosom silang
    cross_chromosome = chromosome[[(i == True) for i in flag]]
    print("Cross chromosome :",cross_chromosome)
    len_cross_chrom = len(cross_chromosome)
    
    # Calculating cross values  
    #/// Menghitung nilai silang
    cross_values = np.random.randint(1,3,len_cross_chrom)
    print("Cross Values :",cross_values)
    
    cpy_chromosome = np.zeros(cross_chromosome.shape)
    
    # Performing Cross-Over  
    #/// Melakukan Cross-Over
    
    # Copying the chromosome values for calculations 
    #/// Menyalin nilai kromosom untuk perhitungan
    for i in range(cross_chromosome.shape[0]):
        cpy_chromosome[i , :] = cross_chromosome[i , :]
        
    if len_cross_chrom == 1:
        cross_chromosome = cross_chromosome
    else :
        for i in range(len_cross_chrom):
            c_val = cross_values[i]
            if i == len_cross_chrom - 1 :
                cross_chromosome[i , c_val:] = cpy_chromosome[0 , c_val:]
            else :
                cross_chromosome[i , c_val:] = cpy_chromosome[i+1 , c_val:]
        
    print("Crossovered Chromosome :",cross_chromosome)
    
    index_chromosome = 0
    index_newchromosome = 0
    for i in flag :
        if i == True :
            chromosome[index_chromosome, :] = cross_chromosome[index_newchromosome, :]
            index_newchromosome = index_newchromosome + 1
        index_chromosome = index_chromosome + 1 
    
    print("New Chromosomes:", chromosome)
    
    # Calculating the total no. of generations 
    #/// Menghitung total no. dari generasi
    a ,b = chromosome.shape[0] ,chromosome.shape[1]
    total_gen = a*b
    print("Total Generations :",total_gen)
    
    #mutation rate = pm 
    #/// tingkat mutasi = pm
    pm = 0.1
    no_of_mutations = int(np.round(pm * total_gen))
    print("No. of Mutations :" ,no_of_mutations)
    
    # Calculating the Generation number 
    #/// Menghitung nomor Generasi
    gen_num = np.random.randint(0,total_gen - 1, no_of_mutations)
    print(" Generated Random Numbers : " , gen_num)
    
    # Generating a random number which can replace the selected chromosome to be mutated 
    #6/// Menghasilkan nomor acak yang dapat menggantikan kromosom yang dipilih untuk dimutasi


    Replacing_num = np.random.randint(0,30, no_of_mutations)
    print(" Numbers to be replaced : " , Replacing_num)
    
    for i in range(no_of_mutations):
        a = gen_num[i]
        row = a//4
        col = a%4
        chromosome[row , col] = Replacing_num[i]
    
    print(" Chromosomes After Mutation : " , chromosome)
  
    epoch = epoch + 1

Streaming output truncated to the last 5000 lines.
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]]
Random Values : [0.796898427756582, 0.9736692338930834, 0.55801406871383, 0.27156962363851334, 0.05191645619795693, 0.6179181686348608]
Flagged Values : [False False False  True False False]
Cross chromosome : [[17.  3.  2.  0.]]
Cross Values : [2]
Crossovered Chromosome : [[17.  3.  2.  0.]]
New Chromosomes: [[17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]]
Total Generations : 24
No. of Mutations : 2
 Generated Random Numbers :  [3 9]
 Numbers to be replaced :  [23 11]
 Chromosomes After Mutation :  [[17.  3.  2. 23.]
 [17.  3.  2.  0.]
 [17. 11.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]
 [17.  3.  2.  0.]]
Fitness object : [91.  1. 15.  1.  1.  1.]
Fitness : [0.01086957 0.5        0.0625     0.5        0.5        0.5       ]
Total : 2.0733695652173916
Probability : [0.00524246 0.24115334 0.03014417 0.2411533